services:
  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=lambda,apigateway
      - DEBUG=1
      - LAMBDA_EXECUTOR=local
      - LAMBDA_REMOVE_CONTAINERS=true
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./lambda:/opt/code/localstack/lambda"
    networks:
      - localstack-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  api-deployer:
    build: 
      context: ./deploy
      dockerfile: Dockerfile
    depends_on:
      localstack:
        condition: service_healthy
    networks:
      - localstack-network
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  consumer:
    build:
      context: ./consumerapp
      dockerfile: Dockerfile
    depends_on:
      - api-deployer
    networks:
      - localstack-network
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

networks:
  localstack-network:
    driver: bridge
